version: "3.8"
services:
  broker:
    image: eclipse-mosquitto
    container_name: broker_mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
volumes:
  config:
  data:
  log:
networks:
  default:
    name: broker-network
